run_dir: /root/25DFT/fairchem/checkpoint
data_root_dir: /root/25DFT/data
mode: LOCAL
device: CUDA
ranks_per_node: 1
dataloader_workers: 8
timeout_hr: 72
debug: False
mem_gb: 40
cpus_per_task: 10
partition: scavenge
additional_parameters: null
